#!ESTE ARCHIVO ES UN TEMPLATE, NO CAMBIARLO EN ABSOLUTO.
name: ğŸ§ªExample Test in CI Pipeline with Cypress
run-name: ${{github.actor}}ğŸ‘¨ğŸ»â€ğŸ”¬ ran Test in ${{github.ref_name}}

# on:
#     push:
#         branches-ignore: [main, QA]
#*Esto indica que se ejecutarÃ¡ con PUSH o MERGE en cualquier rama que no sea 'main' ni 'QA'

on: [workflow_dispatch] #Esta opciÃ³n es  para este Tutorial, para que no se ejecute en CI.

jobs:
    #* Este es un Nombre de este Job, puedes dejarlo como estÃ¡.
    TestSuite:
        #* Este parÃ¡metro indica que se correrÃ¡ en un Sistema Operativo. No cambiar.
        runs-on: ubuntu-latest

        #todo: AquÃ­ a continuaciÃ³n vamos a definir quÃ© vamos a correr de Postman:
        steps:
            #* Este paso, copia y pega literalmente el repo que tenemos.
            - name: ğŸ“˜Checkout Repo
              uses: actions/checkout@v3
              #* el Name es opcional, e indica el nombre del Step. Uses es la dependencia.

            - name: ğŸ’¿Set up JAVA 20 with Maven
              uses: actions/setup-java@v3
              with:
                  java-version: '20'
                  distribution: 'temurin'
                  cache: maven
              #* El with se usa para indicar quÃ© parÃ¡metro se usa con la dependencia.
              #* Considera que el with dependerÃ¡ del uso de la dependencia.

            - name: ğŸ§¬Install All Dependencies with Maven
              run: mvn -B package --file pom.xml

              #! AQUÃ DEBES MODIFICAR el Test Suite a ejecutar.
              #todo: Agrega el tu path de archivo de prueba para ejecutar:
            - name: ğŸ§ªRun Selenium tests
              run: mvn clean verify -Dit.test=FirstTest -Dheadless=true
